//! Automated call testing applications.
//!
//! Port of app_test.c from Asterisk C. Provides TestClient() and
//! TestServer() applications for automated call quality testing.
//! The server answers and plays tones, the client calls and measures
//! audio quality, producing a report file.

use crate::{DialplanApp, PbxExecResult};
use asterisk_core::channel::Channel;
use tracing::{info, warn};

/// Test report generated by TestClient.
#[derive(Debug, Clone, Default)]
pub struct TestReport {
    /// Test identifier.
    pub test_id: String,
    /// Number of audio frames sent.
    pub frames_sent: u64,
    /// Number of audio frames received.
    pub frames_received: u64,
    /// Number of lost frames.
    pub frames_lost: u64,
    /// Percentage of frames received.
    pub receive_pct: f64,
    /// Jitter measurement (ms).
    pub jitter_ms: f64,
}

impl TestReport {
    /// Format report for file output.
    pub fn to_string_report(&self) -> String {
        format!(
            "TestID: {}\nFramesSent: {}\nFramesRecv: {}\nFramesLost: {}\nRecvPct: {:.1}%\nJitter: {:.1}ms\n",
            self.test_id,
            self.frames_sent,
            self.frames_received,
            self.frames_lost,
            self.receive_pct,
            self.jitter_ms,
        )
    }
}

/// The TestServer() dialplan application.
///
/// Usage: TestServer()
///
/// Answers the channel and plays a sequence of test tones (1004 Hz milliwatt)
/// that the TestClient can measure. Runs until the client hangs up.
pub struct AppTestServer;

impl DialplanApp for AppTestServer {
    fn name(&self) -> &str {
        "TestServer"
    }

    fn description(&self) -> &str {
        "Automated call test server - plays test tones"
    }
}

impl AppTestServer {
    /// Execute the TestServer application.
    pub async fn exec(channel: &mut Channel, _args: &str) -> PbxExecResult {
        info!("TestServer: channel '{}' starting test server", channel.name);

        // In a real implementation:
        // 1. Answer channel
        // 2. Set format to slin
        // 3. Send tone frames with sequence numbers embedded
        // 4. Wait for hangup

        PbxExecResult::Success
    }
}

/// The TestClient() dialplan application.
///
/// Usage: TestClient(testid)
///
/// Calls out, receives test tones from TestServer, measures audio
/// quality (frame loss, jitter), and writes a report file.
///
/// Report is written to /var/log/asterisk/testreport_<testid>.txt
pub struct AppTestClient;

impl DialplanApp for AppTestClient {
    fn name(&self) -> &str {
        "TestClient"
    }

    fn description(&self) -> &str {
        "Automated call test client - measures audio quality"
    }
}

impl AppTestClient {
    /// Execute the TestClient application.
    pub async fn exec(channel: &mut Channel, args: &str) -> PbxExecResult {
        let test_id = args.trim();

        if test_id.is_empty() {
            warn!("TestClient: requires test ID argument");
            return PbxExecResult::Failed;
        }

        info!("TestClient: channel '{}' test '{}'", channel.name, test_id);

        // In a real implementation:
        // 1. Set format to slin
        // 2. Read audio frames from channel
        // 3. Track sequence numbers, measure loss and jitter
        // 4. After hangup, write report file

        PbxExecResult::Success
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_report_format() {
        let report = TestReport {
            test_id: "test1".to_string(),
            frames_sent: 1000,
            frames_received: 980,
            frames_lost: 20,
            receive_pct: 98.0,
            jitter_ms: 5.2,
        };
        let s = report.to_string_report();
        assert!(s.contains("TestID: test1"));
        assert!(s.contains("FramesLost: 20"));
    }

    #[tokio::test]
    async fn test_server_exec() {
        let mut channel = Channel::new("SIP/test-001");
        let result = AppTestServer::exec(&mut channel, "").await;
        assert_eq!(result, PbxExecResult::Success);
    }

    #[tokio::test]
    async fn test_client_exec() {
        let mut channel = Channel::new("SIP/test-001");
        let result = AppTestClient::exec(&mut channel, "test1").await;
        assert_eq!(result, PbxExecResult::Success);
    }
}
